### ISSUE TITLE
TypeError: no implicit conversion of nil into String

### ISSUE THREAD

**Issue by mjurin** [cakejelly/layer-api#10]
Hi,

when calling the function to_s on a identity_token I get TypeError: no implicit conversion of nil into String, because there are no substitutions when key.gsub!("\\n","\n") is called and a nil is returned instead.

Any special reason why you dont use just gsub ?

best regards,
Marko

**Comment by cakejelly** [comment]
Hey Marko, cheers for reporting.

No real reason, this was just a specific use-case i've experienced previously, completely overlooked the effects of using `gsub!`. Happy to change to `gsub` if it works :) I should be able to push a fix later on today. Alternatively, you're more than welcome to submit a PR in the mean time

**Comment by mjurin** [comment]
Done. But some tests fail because of env variables. How can I set them?

**Comment by cakejelly** [comment]
Fixed in #11
