### ISSUE TITLE
Get last message with conversation

### ISSUE THREAD

**Issue by mjurin** [cakejelly/layer-api#16]
Hi,

another question. I was looking over the layer documentation and I cant find a way to get a list of conversations for a user and inside the conversation also the last message (with a single call). 

Right now I am calling the message list for each conversation and it will be become slow in the future with a lot of conversations.

thx

**Comment by cakejelly** [comment]
Hi Marko,

You should be able to get all conversations for a user with: 
```
client = Layer::Platform::Client.new(api_token: "your_api_token", app_id: "your_app_id")
user = client.users.find("user_id")
conversations = user.conversations.list
```

Then each conversation in the array should have a `last_message` attribute. So you could iterate with something like:

```
conversations.each{ |conv| p conv.last_message }
```

**Comment by mjurin** [comment]
Wow, this works :) 

Thanks for the help.
