### ISSUE TITLE
Sorting conversations

### ISSUE THREAD

**Issue by daninfpj** [cakejelly/layer-api#18]
You should be able to sort the conversations, as such:

`conversations = user.conversations.list(sort_by: 'last_message')`

However, because of the way the list method was written, that doesn't work. Instead of adding the params to the query parameters, it sends a JSON encoded string as the body of the request, which doesn't make sense for a GET request.

**Comment by daninfpj** [comment]
#19

**Comment by cakejelly** [comment]
Cheers for spotting this, i've never really used the filtering params previously so it completely slipped under my radar.

Just one small issue with your PR, which i've commented on but other than that will be happy to merge

**Comment by cakejelly** [comment]
Fixed in #19
