### ISSUE TITLE
Unable to update identity

### ISSUE THREAD

**Issue by stevefusaro** [cakejelly/layer-api#21]
Here is my code:

``` ruby
def update_layer_identity(user)
    operations = [
      {operation: "set", property: "display_name", value: "Hello Friend"}
    ]
    layer_user = layer_client.users.find(user.uuid)
    layer_user.update(operations)
end
```

And I get the following error:

```
Layer responded with status 422: {"url":"https://developer.layer.com/docs/platform","data":{"property":"display_name"},"code":9,"id":"invalid_operation","message":"Patch operation \"set\" on \"display_name\" is not allowed."}
```

Same thing happens when I try to update first_name, last_name and phone_number. I'm able to PATCH successfully using curl, so it must be an issue with this Library?

**Comment by cakejelly** [comment]
Hey @stevefusaro,

Apologies for the delayed response, I haven't really looked at this library or layer in a long time. It does indeed look like a bug. I'll spend some time within the next few days to have a look and get it fixed. A PR is also welcome if you fancy it :)

**Comment by cakejelly** [comment]
Took a look and noticed you're attempting to update the user instead of the identity. The following should work:

```ruby
def update_layer_identity(user)
    operations = [
      {operation: "set", property: "display_name", value: "Hello Friend"}
    ]
    layer_user = layer_client.users.find(user.uuid)
    layer_user.update_identity(operations)
end
```

Closing this for now but feel free to reopen if you run into more issues
