### ISSUE TITLE
invalid_app_id

### ISSUE THREAD

**Issue by phyxavier** [cakejelly/layer-api#5]
Tested the same App Id on layer-ruby gem and it works but somehow it doesn't work with this  gem.

Layer::Error: Layer responded with status 403: {"id":"invalid_app_id","code":2,"message":"The referenced App ID is invalid.

**Comment by cakejelly** [comment]
Hmm strange.. I'll take a look, thanks for reporting.

What method call threw this error out of curiosity?

Also, if you get the chance, would you mind pasting a snippet of how you're instantiating the client

**Comment by phyxavier** [comment]
thanks for the quick response
platform = Layer::Platform::Client.new(api_token: "token", app_id: "xxxxxx-xxxx-xxx-xxx-xxxx")
conv = platform.conversations.find("xxx-xx-xx-xxx-xxxx")

**Comment by cakejelly** [comment]
Is it possible that there was a typo in your app id? I can't seem to reproduce at all

**Comment by cakejelly** [comment]
Turns out you were right, good spot. I never noticed this previously as I was always using default ENV variables when instantiating. Should be fixed now :)
